# Generated by Django 2.2.4 on 2019-09-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('line_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('is_black', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('work_type', models.IntegerField(choices=[(1, '單'), (2, '雙')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='reservation_time')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Customer')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Master', unique_for_date='datetime')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MasterGroup'),
        ),
    ]
