# Generated by Django 2.2.4 on 2019-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_reservation_has_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
