# Generated by Django 2.2.4 on 2019-09-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_reservation_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastergroup',
            name='descript',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mastergroup',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='line_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
