# Generated by Django 2.2.4 on 2019-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191007_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergroup',
            name='image',
            field=models.ImageField(upload_to='master'),
        ),
    ]
