# Generated by Django 2.2.4 on 2019-10-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_reservation_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Master'),
        ),
    ]
