# Generated by Django 2.2.4 on 2020-01-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_mastergroup_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='master')),
                ('brief_intro', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=1024)),
            ],
        ),
    ]
