# Generated by Django 2.2.4 on 2020-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_auto_20200102_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
