# Generated by Django 2.2.4 on 2020-01-02 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_auto_20200102_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
