# Generated by Django 2.2.4 on 2020-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_auto_20200118_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancel_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
