# Generated by Django 2.2.4 on 2020-01-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_openingdays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningDays',
            new_name='OpeningDay',
        ),
    ]
