# Generated by Django 2.2.4 on 2020-01-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_auto_20200131_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingday',
            name='days',
            field=models.IntegerField(),
        ),
    ]
