# Generated by Django 2.2.4 on 2020-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0022_customer_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='introducer',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
