# Generated by Django 2.2.4 on 2020-01-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_auto_20200131_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='introducer',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
