# Generated by Django 2.2.4 on 2020-01-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_question_answer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_image',
        ),
    ]
