# Generated by Django 2.2.4 on 2020-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0027_question_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answer'),
        ),
    ]
