# Generated by Django 2.2.4 on 2020-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0028_auto_20200131_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
