# Generated by Django 2.2.4 on 2020-02-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0030_auto_20200205_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
