# Generated by Django 2.2.4 on 2020-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0031_auto_20200205_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='group',
        ),
        migrations.AddField(
            model_name='master',
            name='group',
            field=models.ManyToManyField(null=True, related_name='groups', to='test_app.MasterGroup'),
        ),
    ]
