# Generated by Django 2.2.4 on 2020-08-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0033_auto_20200706_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_black',
            field=models.BooleanField(default=False, verbose_name='blacklist'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='has_ensured_remind',
            field=models.BooleanField(default=False, verbose_name='客人已確認提醒'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='has_sent_remind',
            field=models.BooleanField(default=False, verbose_name='系統已傳送提醒訊息'),
        ),
    ]
